### ISSUE TITLE
rt-ax68u

### ISSUE THREAD

**Issue by alexins** [Adamm00/amcfwm#4]
You have made some typos and therefore the build for rt-ax68u does not work.
Here is a patch that fixes the build errors:

[fix_ax68u.zip](https://github.com/Adamm00/amcfwm/files/6836637/fix_ax68u.zip)

**Comment by kernol51** [comment]
@alexins - Dropping a ZIP file with zero explanation nor transparency - is hardly likely to be applied by members ... especially when this is your FIRST activity in Github and the only other thing you have done is cloned Merlinware for Asus routers !!!

**Comment by alexins** [comment]
The patch text can be viewed here: https://pastebin.com/Uz8vfuTy

**Comment by Adamm00** [comment]
The rtax68 branch is [used upstream](https://github.com/RMerl/asuswrt-merlin.ng/blob/b450eefd91df0bdfdfa85ec3703263cc76231530/tools/build-all#L64) so I am also using it here. Upon closer inspection, it seems it hasn't been merged since March so not sure what the deal is there, might be worth raising this with merlin.

In any case, thanks for the useful bug reports.
